# Generated by Django 5.2.6 on 2025-10-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationary_app', '0003_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
