# Generated by Django 5.2.6 on 2025-10-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary_app', '0005_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_design',
            field=models.BooleanField(default=False),
        ),
    ]
