# Generated by Django 5.2.6 on 2025-10-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationary_app', '0006_productimage_is_design'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
