# Generated by Django 5.2.6 on 2025-10-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary_app', '0008_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
