# Generated by Django 5.2.6 on 2025-10-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary_app', '0010_alter_cart_date_added_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='GST rate in %', max_digits=5),
        ),
    ]
