# Generated by Django 5.2.6 on 2025-10-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationary_app', '0013_alter_category_options_category_parent_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
