# Generated by Django 5.2.6 on 2025-10-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationary_app', '0018_alter_category_options_alter_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
