# Generated by Django 5.2.6 on 2025-10-17 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary_app', '0019_remove_category_slug_remove_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stationary_app.category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
