# Generated by Django 5.2.6 on 2025-10-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary_app', '0021_remove_product_category_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
