# Generated by Django 5.2.6 on 2025-10-25 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationary_app', '0023_remove_product_subcategory_subsubcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the admin panel and internal reference.', max_length=100)),
                ('section_type', models.CharField(choices=[('BANNER_FULL', 'Full-Width Banner'), ('BANNER_HALF', 'Two-Column Banner'), ('FEATURED_PRODUCTS', 'Featured Products Grid'), ('FEATURED_SUBCATEGORIES', 'Featured SubCategories')], default='BANNER_FULL', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Main image for the section (e.g., for a full banner).', null=True, upload_to='homepage_sections/')),
                ('link_url', models.CharField(blank=True, help_text='URL the section links to (e.g., /shop/).', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=100, help_text='Order of display on the homepage (lower number comes first).', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Homepage Section/Banner',
                'verbose_name_plural': 'Homepage Sections/Banners',
                'ordering': ['display_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.IntegerField(default=100, help_text='Order of display on the homepage (lower number comes first).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the category on the homepage.', null=True, upload_to='category_images/'),
        ),
    ]
