# Generated by Django 5.2.6 on 2025-10-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationary_app', '0024_homepagesection_alter_category_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageSection',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
